
POST http://localhost:5000/api/bookingForm
Content-Type: application/json

{
   "ownerName": "",
   "phone": "",
   "email": "",
   "petName1": "",
   "petName2": "",
   "petAge1": "",
   "petAge2": "",
   "numberOfGuests": "1",
   "checkIn": "",
   "checkOut": ""
}

